export const CSS = {
  CursorStyles: {
    AUTO: "auto",
    DEFAULT: "default",
    POINTER: "pointer",
    TEXT: "text",
    MOVE: "move",
    NOT_ALLOWED: "not-allowed",
    CROSSHAIR: "crosshair",
    HELP: "help",
    WAIT: "wait",
    GRAB: "grab",
    GRABBING: "grabbing",
    EW_RESIZE: "ew-resize",
    NS_RESIZE: "ns-resize",
    NE_RESIZE: "ne-resize",
    NW_RESIZE: "nw-resize",
    SE_RESIZE: "se-resize",
    SW_RESIZE: "sw-resize",
    NESW_RESIZE: "nesw-resize",
    NWSE_RESIZE: "nwse-resize",
    COL_RESIZE: "col-resize",
    ROW_RESIZE: "row-resize",
    ALL_SCROLL: "all-scroll",
    VERTICAL_TEXT: "vertical-text",
    CELL: "cell",
    CONTEXT_MENU: "context-menu",
    ALIAS: "alias",
    COPY: "copy",
    NO_DROP: "no-drop",
    NONE: "none",
    PROGRESS: "progress",
    ZOOM_IN: "zoom-in",
    ZOOM_OUT: "zoom-out",
  },
};
